# Generated by Django 3.1.3 on 2022-01-24 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0002_auto_20220124_0201'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='choice_text',
            field=models.TextField(default='text'),
        ),
        migrations.AddField(
            model_name='choice',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='grade',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='question',
            name='question_text',
            field=models.TextField(default='text'),
        ),
    ]
